#!/bin/bash

# Install Nginx web server
sudo apt-get update
sudo apt-get install nginx -y

# Create a new configuration file for the redirection
sudo touch /etc/nginx/sites-available/redirect_me.conf
sudo chmod 666 /etc/nginx/sites-available/redirect_me.conf

# Edit the configuration file to include the redirection
echo "server {
    listen 80;
    server_name http://mulubrhan.tech/;
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;
}" >> /etc/nginx/sites-available/redirect_me.conf

# Create a symbolic link to enable the configuration
sudo ln -s /etc/nginx/sites-available/redirect_me.conf /etc/nginx/sites-enabled/

# Test the configuration and restart Nginx
sudo nginx -t
sudo service nginx restart